### ISSUE TITLE
'Cards to draw' input field has got no default value

### ISSUE THREAD

**Issue by emosGambler** [Dakova1994/Angular-Test#12]
Currently 'Cards to draw' input field looks like this:

-->
![cards_to_draw](https://i.imgur.com/a5QZtQq.png)
-->

As can be seen, this field is empty on start. We need to put there value of 1, because it is the minimum value that can be there.

Requirement 1:
Add default value of 1 to 'Cards to draw' input field.

**Comment by Dakova1994** [comment]
done

**Comment by emosGambler** [comment]
Are the changes deployed to develop?
