### ISSUE TITLE
Remove additional "Projekt" directory from project tree

### ISSUE THREAD

**Issue by emosGambler** [Dakova1994/Angular-Test#14]
Currently we have unnecessary "projekt" directory in our project:

![additional_directory](https://i.imgur.com/urJDTbt.png)

Requirement 1.
Remove "Projekt" folder, so that all the files inside this folder are now next to "README.md", but be careful to not mess it up :).

**Comment by Dakova1994** [comment]
Working on feature/delete-useless-folder
