### ISSUE TITLE
[BUG] When exactly 52 cards are drawn, error message is shown

### ISSUE THREAD

**Issue by emosGambler** [Dakova1994/Angular-Test#33]
**Steps to reproduce:**
1. Draw 52 cards

**Result:**
1. 'Not enough cards to draw!' message is shown

**Expected result:**
1. No message should be shown now

**Comment by Dakova1994** [comment]
For now i dont have any idea to do it :(

**Comment by Dakova1994** [comment]
It work
![image](https://user-images.githubusercontent.com/32669409/38696648-0a54ab38-3e90-11e8-8f66-6988cef74906.png)

**Comment by emosGambler** [comment]
Yeah. But now if we want more than 52 cards, there is no error message :)

![https://i.imgur.com/v09QXZR.png](https://i.imgur.com/v09QXZR.png)

**Comment by emosGambler** [comment]
Ok, this is fixed now.
