### ISSUE TITLE
[BUG] Error message is appearing too many times for some cases

### ISSUE THREAD

**Issue by emosGambler** [Dakova1994/Angular-Test#37]
**Steps:**
1. Draw 52 cards
2. Check 'new deck' checkbox
3. Draw 1 card

**Result:**
1. Error message appears.

**Expected result:**
1. No error message should appear

**Comment by Dakova1994** [comment]
Message dont show but we have other problem, becouse when i make that steps, on the third step i dont get any cards.....

**Comment by emosGambler** [comment]
Yeah. Let me think about it!

**Comment by emosGambler** [comment]
But this issue is solved.

**Comment by emosGambler** [comment]
Ok, so this took me a while to figure out, but the problem existed, because application was working as follows:

Prerequisites: All cards are drawn; 'new deck' checkbox is marked as checked
1) After 'draw' button is clicked, new deck is requested (`this.currentDeck` has got **still old value**)
2) Cards are being drawn **from the old deck**, but it cannot be done, so no cards are shown on the UI
3) Current deck is **now brand new**
4) User clicks 'draw' button again and **this time cards are drawn, because new deck is served**

I have pushed a solution, so you can check it out. I don't believe it is a best one, but now it works.
