### ISSUE TITLE
Draw button should draw cards from current deck

### ISSUE THREAD

**Issue by emosGambler** [Dakova1994/Angular-Test#5]
When implemented, 'Draw' button always creates new deck. We want it to draw cards from the current deck.

Requirement 1.
Change logic to 'Draw' button., so that it draws cards from current deck.

**Comment by Dakova1994** [comment]
It is done?

**Comment by emosGambler** [comment]
If so, then close please.

3 mar 2018 19:37 "Dakova1994" <notifications@github.com> napisał(a):
